description:
  list of recipes

title:
  _has:
    input: text

imageUrl:
  _label: URL
  _has:
    input: text
    type: url
    validate:
      required: true
    help: Must be an image URL

recipeName:
  _label: name
  _has: 
    input: text

score:
  _label: score
  _has:
    input: range
    min: 0
    max: 5

reviews:
  _label: reviews
  _has:
    input: range
    min: 0
    max: 100

_groups:
  settings:
    fields:
      - title
      - recipeName
      - score
      - reviews
      - imageUrl (Image)
    _placeholder:
      text: Explore
      height: 250px
      ifEmpty: imageUrl

