description:
  list of recipes

title:
  _has:
    input: text

imageUrl:
  _label: URL
  _has:
    input: text
    type: url
    help: Must be an image URL

recipeName:
  _label: name
  _has: 
    input: text

reviews:
  _label: reviews
  _has:
    input: range
    min: 0
    max: 100