description: |
  In Article Single Image

title:
  _label: Recipe title
  _publish: pageTitle # Listened to by the `meta-title` component
  _has:
    input: text

author:
  _label: author
  _has:
    input: text

recipeDescription:
  _label: Recipe description
  _has:
    input: text

reviews:
  _label: quantity of reviews
  _has:
    input: range
    min: 0
    max: 10000

photos:
  _label: quantity of photos
  _has:
    input: range
    min: 0
    max: 10000

madeIt:
  _label: quantity of people that have made it
  _has:
    input: range
    min: 0
    max: 10000

imageUrl:
  _label: URL
  _has:
    input: text
    type: url
    validate:
      required: true
    help: Must be an image URL

_groups:
  settings:
    fields:
      - title
      - author
      - recipeDescription
      - reviews
      - photos
      - madeIt
      - imageUrl (Image)
    _placeholder:
      text: New Recipe
      height: 250px
      ifEmpty: imageUrl
